### PR TITLE
Add i18n string (Add Chinese)

### PR DESCRIPTION
**Pull request by wangxiaoerYah**
Add support for Chinese

### CODE REVIEW

**Comment by xeffyr** [comment]
Sorry, but I do not accept PRs for this project.

Also, localization is not supported as translation through `strings.xml` will be incomplete.

**Comment by ichit** [comment]
hi, please could you help me explain how to make docker run on alpine term. i have followed the docker alpine page and installed docker but each time i run it, i get the massage "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docke?" i really want to use docker on this app. thanks

**Comment by xeffyr** [comment]
From root shell:
```
apk add docker
service docker start
```
Monitor log file `/var/log/docker.log` to check whether `containerd` is actually started. If there was error about timeout or similar (I had it on first launch), do `service restart docker`.

Docker service may take about 1 minute to be fully initialized.

**Comment by ichit** [comment]
hi, i did as you said and when i ran service restart docker, i got service restart does not exist

**Comment by xeffyr** [comment]
Sorry, it was a typo. I have corrected to `service docker restart`.

**Pull request closed without merging**
